version: "3"

services:
  postgres:
    container_name: backend-postgres
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    container_name: backend-redis
    image: bitnami/redis:7.0.2
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "redis"
    volumes:
      - ./data/redis:/data